"""create_table

Revision ID: 878869ed09d4
Revises: 
Create Date: 2024-04-28 00:57:54.520867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '878869ed09d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=68), nullable=False),
    sa.Column('last_name', sa.String(length=68), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.drop_table('bot_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_user',
    sa.Column('telegram_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=68), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=68), autoincrement=False, nullable=True),
    sa.Column('locale', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id', name='bot_user_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
